/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafemanagementsystem;

import dao.newpackage.Userdao;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author USER
 */
public class login extends javax.swing.JFrame {

    public String mailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        btnLogin.setEnabled(true);
    }

    public void clear() {
        txtmail.setText("");
        txtPassword.setText("");
        btnLogin.setEnabled(false);
    }

    public void validateFields() {
        String mail = txtmail.getText();
        String password = txtPassword.getText();
        if (mail.matches(mailPattern) && !password.equals("")) {
            btnLogin.setEnabled(true);

        } else {
            btnLogin.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        txtClear = new javax.swing.JButton();
        txtExit = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("     Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 288, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Email:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 170, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 283, 140, 40));

        txtmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 333, 34));

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 332, 33));

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newpackage/login.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        txtClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newpackage/clear.png"))); // NOI18N
        txtClear.setText("Clear");
        txtClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClearActionPerformed(evt);
            }
        });
        getContentPane().add(txtClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 103, -1));

        txtExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newpackage/exit.png"))); // NOI18N
        txtExit.setText("Exit");
        txtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExitActionPerformed(evt);
            }
        });
        getContentPane().add(txtExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 390, -1, 29));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Signup");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, -1, 33));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newpackage/first page background.PNG"))); // NOI18N
        jLabel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel4KeyReleased(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 1370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String mail = txtmail.getText();
        String Password = txtPassword.getText();
        User user = null;
        user = Userdao.Login(mail, Password);
        if (user == null) {
            JOptionPane.showMessageDialog(
                    null,
                    "<html><b style='color:red'>Incorrect username or password</b></html>",
                    "Message",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            if (user.getStatus().equals("false")) {
                ImageIcon icon = new ImageIcon("src/popupIcon/wait.png");
                JOptionPane.showMessageDialog(null, "<html><b>wait for Admin Approval</b></html>", "Message",
                        JOptionPane.INFORMATION_MESSAGE, icon);
                clear();
            }
            if (user.getStatus().equals("true")) {
                setVisible(false);
                // Check if admin
                boolean isAdmin = mail.equals("admin@gmail.com");
                new Home(mail, isAdmin).setVisible(true);

            }
        }

    }// GEN-LAST:event_btnLoginActionPerformed

    private void txtClearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtClearActionPerformed
        clear(); // TODO add your handling code here:
    }// GEN-LAST:event_txtClearActionPerformed

    private void txtExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtExitActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to close application", "Select",
                JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
        // TODO add your handling code here:
    }// GEN-LAST:event_txtExitActionPerformed

    private void txtmailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtmailActionPerformed
        validateFields(); // TODO add your handling code here:
    }// GEN-LAST:event_txtmailActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);
        new ForgotPassword().setVisible(true);
    }// GEN-LAST:event_jButton4ActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtPasswordActionPerformed
        validateFields(); // TODO add your handling code here:
    }// GEN-LAST:event_txtPasswordActionPerformed

    private void jLabel4KeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jLabel4KeyReleased
        // TODO add your handling code here:
    }// GEN-LAST:event_jLabel4KeyReleased

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtPasswordKeyReleased
        // TODO add your handling code here:
    }// GEN-LAST:event_txtPasswordKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
        setVisible(false);
        new Signup().setVisible(true);// TODO add your handling code here:
    }// GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton txtClear;
    private javax.swing.JButton txtExit;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtmail;
    // End of variables declaration//GEN-END:variables
}
